all:
  children:
    master:
      hosts:
        k3s-cp-0.example.internal:
          ansible_hostname: k3s-cp-0
          ansible_host: 192.0.2.70
        k3s-cp-1.example.internal:
          ansible_hostname: k3s-cp-1
          ansible_host: 192.0.2.71
        k3s-cp-2.example.internal:
          ansible_hostname: k3s-cp-2
          ansible_host: 192.0.2.72
    node:
      hosts:
        k3s-worker-0.example.internal:
          ansible_hostname: k3s-worker-0
          ansible_host: 192.0.2.80
        k3s-worker-1.example.internal:
          ansible_hostname: k3s-worker-1
          ansible_host: 192.0.2.81
        k3s-worker-2.example.internal:
          ansible_hostname: k3s-worker-2
          ansible_host: 192.0.2.82
    k3s_cluster:
      children:
        master: {}
        node: {}
